name: Basic CI pipeline
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.6

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: build/libs

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.6

      - name: Build with Gradle
        run: ./gradlew test

      - name: Upload build reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-reports
          path: build/reports/

  build-docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: package
          path: build/libs

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: mvkoval/hsa-cicd-app:${{ github.sha }}

  deploy:
    needs: build-docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker stop webapp || true
            docker rm webapp || true
            docker pull mvkoval/hsa-cicd-app:${{ github.sha }}
            docker run -d --name webapp -p 8080:80 mvkoval/hsa-cicd-app:${{ github.sha }}


